// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjNObQ_7DQ6Me3pW0TB3MyGKt90H0UuY',
    appId: '1:1094527829789:web:648db4c93dc79e6f65c3f4',
    messagingSenderId: '1094527829789',
    projectId: 'helplink-2e363',
    authDomain: 'helplink-2e363.firebaseapp.com',
    storageBucket: 'helplink-2e363.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgX5p2iLi1Knk9YOOVZo2yk3q9Ad51xF4',
    appId: '1:1094527829789:android:4cba8a148a34657d65c3f4',
    messagingSenderId: '1094527829789',
    projectId: 'helplink-2e363',
    storageBucket: 'helplink-2e363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgi4_e0QPXOh0gKKoj-go1aTKd2og2OE',
    appId: '1:1094527829789:ios:82a4fa39c9c558b765c3f4',
    messagingSenderId: '1094527829789',
    projectId: 'helplink-2e363',
    storageBucket: 'helplink-2e363.firebasestorage.app',
    iosBundleId: 'com.example.part1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXgi4_e0QPXOh0gKKoj-go1aTKd2og2OE',
    appId: '1:1094527829789:ios:82a4fa39c9c558b765c3f4',
    messagingSenderId: '1094527829789',
    projectId: 'helplink-2e363',
    storageBucket: 'helplink-2e363.firebasestorage.app',
    iosBundleId: 'com.example.part1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZjNObQ_7DQ6Me3pW0TB3MyGKt90H0UuY',
    appId: '1:1094527829789:web:6003719f21a291f965c3f4',
    messagingSenderId: '1094527829789',
    projectId: 'helplink-2e363',
    authDomain: 'helplink-2e363.firebaseapp.com',
    storageBucket: 'helplink-2e363.firebasestorage.app',
  );

}